import { describe, expect, it } from 'vitest';
import { API_OPERATIONS, findDrift, renderApiOutputs, type ApiOutputs } from './api-outputs.ts';
import type { OpenApiDocument } from './filter-openapi.ts';

function publishedSpec(): OpenApiDocument {
  return {
    openapi: '3.1.0',
    info: { title: 'Probara API', version: '1.0.0' },
    paths: {
      '/api/v1/projects/{projectId}/reports': {
        post: {
          operationId: 'submitReport',
          parameters: [
            { name: 'projectId', in: 'path', required: true, schema: { type: 'string' } },
          ],
          responses: {
            '201': {
              description: 'Report recorded',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: { recorded: { type: 'integer' } },
                    required: ['recorded'],
                  },
                },
              },
            },
          },
        },
      },
      '/api/v1/projects': {
        get: { operationId: 'listProjects', responses: { '200': { description: 'ok' } } },
      },
    },
  };
}

describe('renderApiOutputs', () => {
  it('writes the filtered spec as pretty JSON ending with a newline', async () => {
    const outputs = await renderApiOutputs(publishedSpec(), 'https://docs.example.test/v1.json');
    const spec = JSON.parse(outputs.spec) as { paths: Record<string, unknown> };

    expect(outputs.spec.endsWith('}\n')).toBe(true);
    expect(outputs.spec).toContain('\n  "paths": {');
    expect(Object.keys(spec.paths)).toEqual(['/api/v1/projects/{projectId}/reports']);
  });

  it('generates types for the kept operations only, under a header naming the source', async () => {
    const outputs = await renderApiOutputs(publishedSpec(), './local/v1.json');

    expect(
      outputs.types.startsWith('// Generated by scripts/generate-api.ts from ./local/v1.json.'),
    ).toBe(true);
    expect(outputs.types).toContain('Do not edit.');
    expect(outputs.types).toContain('submitReport');
    expect(outputs.types).toContain('recorded: number');
    expect(outputs.types).not.toContain('listProjects');
  });

  it('asks for the report submission operation', () => {
    expect(API_OPERATIONS).toContainEqual({
      path: '/api/v1/projects/{projectId}/reports',
      method: 'post',
    });
  });
});

describe('findDrift', () => {
  const generated: ApiOutputs = { spec: '{}\n', types: 'export type A = 1;\n' };

  it('reports nothing when the committed files match', () => {
    expect(findDrift(generated, { spec: '{}\n', types: 'export type A = 1;\n' })).toEqual([]);
  });

  it('reports each file that differs or is missing', () => {
    expect(findDrift(generated, { spec: '{ }\n', types: undefined })).toEqual(['spec', 'types']);
    expect(findDrift(generated, { spec: '{}\n', types: 'export type A = 2;\n' })).toEqual([
      'types',
    ]);
  });
});
