import { describe, expect, it } from 'vitest';
import { API_OPERATIONS, findDrift, renderApiOutputs, type ApiOutputs } from './api-outputs.ts';
import type { OpenApiDocument } from './filter-openapi.ts';

function publishedSpec(): OpenApiDocument {
  return {
    openapi: '3.1.0',
    info: { title: 'Probara API', version: '1.0.0' },
    paths: {
      '/api/v1/projects/{projectId}/reports': {
        post: {
          operationId: 'submitReport',
          parameters: [
            { name: 'projectId', in: 'path', required: true, schema: { type: 'string' } },
          ],
          responses: {
            '201': {
              description: 'Report recorded',
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    properties: { recorded: { type: 'integer' } },
                    required: ['recorded'],
                  },
                },
              },
            },
          },
        },
      },
      '/api/v1/runs/{runUlid}/close': {
        post: {
          operationId: 'closeRun',
          responses: { '200': { description: 'Closed run' } },
        },
      },
      '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments:stage': {
        post: {
          operationId: 'stageResultAttachments',
          responses: { '200': { description: 'Staged attachment refs' } },
        },
      },
      '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments': {
        patch: {
          operationId: 'commitResultAttachments',
          responses: { '200': { description: 'Committed attachment list' } },
        },
        delete: {
          operationId: 'deleteResultAttachments',
          responses: { '204': { description: 'Deleted' } },
        },
      },
      '/api/v1/projects': {
        get: { operationId: 'listProjects', responses: { '200': { description: 'ok' } } },
      },
    },
  };
}

describe('renderApiOutputs', () => {
  it('writes the filtered spec as pretty JSON ending with a newline', async () => {
    const outputs = await renderApiOutputs(publishedSpec());
    const spec = JSON.parse(outputs.spec) as { paths: Record<string, unknown> };

    expect(outputs.spec.endsWith('}\n')).toBe(true);
    expect(outputs.spec).toContain('\n  "paths": {');
    expect(Object.keys(spec.paths)).toEqual([
      '/api/v1/projects/{projectId}/reports',
      '/api/v1/runs/{runUlid}/close',
      '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments',
      '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments:stage',
    ]);
  });

  it('generates types for the kept operations only, under a header that names no source', async () => {
    const outputs = await renderApiOutputs(publishedSpec());

    // The same spec read from a file or from the public URL renders the same bytes, so a drift
    // check compares content only.
    expect(
      outputs.types.startsWith(
        '// Generated by scripts/generate-api.ts from the Probara OpenAPI. Do not edit.\n\n',
      ),
    ).toBe(true);
    expect(outputs.types).toContain('submitReport');
    expect(outputs.types).toContain('closeRun');
    expect(outputs.types).toContain('stageResultAttachments');
    expect(outputs.types).toContain('commitResultAttachments');
    expect(outputs.types).toContain('recorded: number');
    expect(outputs.types).not.toContain('listProjects');
    expect(outputs.types).not.toContain('deleteResultAttachments');
  });

  it('asks for the report, run close and result attachment operations', () => {
    expect(API_OPERATIONS).toEqual([
      { path: '/api/v1/projects/{projectId}/reports', method: 'post' },
      { path: '/api/v1/runs/{runUlid}/close', method: 'post' },
      { path: '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments:stage', method: 'post' },
      { path: '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments', method: 'patch' },
    ]);
  });
});

describe('findDrift', () => {
  const generated: ApiOutputs = { spec: '{}\n', types: 'export type A = 1;\n' };

  it('reports nothing when the committed files match', () => {
    expect(findDrift(generated, { spec: '{}\n', types: 'export type A = 1;\n' })).toEqual([]);
  });

  it('reports each file that differs or is missing', () => {
    expect(findDrift(generated, { spec: '{ }\n', types: undefined })).toEqual(['spec', 'types']);
    expect(findDrift(generated, { spec: '{}\n', types: 'export type A = 2;\n' })).toEqual([
      'types',
    ]);
  });
});
