import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';
import { filterOpenApi, type OpenApiDocument, type OperationSelector } from './filter-openapi.ts';

/** The operations `@probara/core` calls. Add an entry here to generate its types. */
export const API_OPERATIONS: readonly OperationSelector[] = [
  { path: '/api/v1/projects/{projectId}/reports', method: 'post' },
];

/** The two committed files, as text: the filtered spec and the generated types. */
export interface ApiOutputs {
  readonly spec: string;
  readonly types: string;
}

export type ApiOutputName = keyof ApiOutputs;

/** Filters the published spec to {@link API_OPERATIONS} and renders both committed files. */
export async function renderApiOutputs(
  published: OpenApiDocument,
  source: string,
): Promise<ApiOutputs> {
  const filtered = filterOpenApi(published, API_OPERATIONS);
  const ast = await openapiTS(filtered as unknown as OpenAPI3, { silent: true });
  const header = `// Generated by scripts/generate-api.ts from ${source}. Do not edit.\n\n`;
  const body = astToString(ast).trimEnd();
  return {
    spec: `${JSON.stringify(filtered, null, 2)}\n`,
    types: `${header}${body}\n`,
  };
}

/** Names the outputs whose committed content is missing or differs from the generated one. */
export function findDrift(
  generated: ApiOutputs,
  committed: Readonly<Record<ApiOutputName, string | undefined>>,
): ApiOutputName[] {
  return (Object.keys(generated) as ApiOutputName[]).filter(
    (name) => committed[name] !== generated[name],
  );
}
