import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';
import { filterOpenApi, type OpenApiDocument, type OperationSelector } from './filter-openapi.ts';

/** The operations `@probara/core` calls. Add an entry here to generate its types. */
export const API_OPERATIONS: readonly OperationSelector[] = [
  { path: '/api/v1/projects/{projectId}/reports', method: 'post' },
  { path: '/api/v1/projects/{projectId}/runs', method: 'post' },
  { path: '/api/v1/runs/{runUlid}/close', method: 'post' },
  { path: '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments:stage', method: 'post' },
  { path: '/api/v1/runs/{runUlid}/results/{resultUlid}/attachments', method: 'patch' },
];

/**
 * The first line of the generated types. It names no source, so the same spec read from a file or
 * from the public URL renders the same bytes and `--check` compares content only.
 */
const HEADER = '// Generated by scripts/generate-api.ts from the Probara OpenAPI. Do not edit.\n\n';

/** The two committed files, as text: the filtered spec and the generated types. */
export interface ApiOutputs {
  readonly spec: string;
  readonly types: string;
}

export type ApiOutputName = keyof ApiOutputs;

/** Filters the published spec to {@link API_OPERATIONS} and renders both committed files. */
export async function renderApiOutputs(published: OpenApiDocument): Promise<ApiOutputs> {
  const filtered = filterOpenApi(published, API_OPERATIONS);
  const ast = await openapiTS(filtered as unknown as OpenAPI3, { silent: true });
  const body = astToString(ast).trimEnd();
  return {
    spec: `${JSON.stringify(filtered, null, 2)}\n`,
    types: `${HEADER}${body}\n`,
  };
}

/** Names the outputs whose committed content is missing or differs from the generated one. */
export function findDrift(
  generated: ApiOutputs,
  committed: Readonly<Record<ApiOutputName, string | undefined>>,
): ApiOutputName[] {
  return (Object.keys(generated) as ApiOutputName[]).filter(
    (name) => committed[name] !== generated[name],
  );
}
