import { describe, expect, it } from 'vitest';
import { renderVersionModule } from './version-module.ts';

describe('renderVersionModule', () => {
  it('renders the version as a string literal under a generated header', () => {
    expect(renderVersionModule('0.1.0')).toBe(
      [
        '// Generated by scripts/sync-version.ts from package.json. Do not edit.',
        '',
        '/** The version of `@probara/core`, sent in the User-Agent. */',
        "export const VERSION = '0.1.0';",
        '',
      ].join('\n'),
    );
  });

  it('keeps a prerelease and build version as it is', () => {
    expect(renderVersionModule('1.2.3-beta.4+build.5')).toContain(
      "export const VERSION = '1.2.3-beta.4+build.5';",
    );
  });

  it('rejects a version that is not semver instead of writing broken code', () => {
    for (const version of ['', '1.2', "1.0.0'; evil()", ' 1.0.0', 'v1.0.0']) {
      expect(() => renderVersionModule(version)).toThrow(/not a semver version/);
    }
  });
});
