/** Renders `src/version.ts` from the package version (written by `sync-version.ts`). */

// SemVer 2.0.0: MAJOR.MINOR.PATCH, then an optional prerelease and build metadata.
const SEMVER =
  /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

/**
 * The source of `src/version.ts`. A literal (rather than reading `package.json` at runtime) keeps
 * core working once an adapter or a user bundles it, where no manifest sits next to the code.
 */
export function renderVersionModule(version: string): string {
  if (!SEMVER.test(version)) {
    throw new Error(`The package version ${JSON.stringify(version)} is not a semver version`);
  }
  return [
    '// Generated by scripts/sync-version.ts from package.json. Do not edit.',
    '',
    '/** The version of `@probara/core`, sent in the User-Agent. */',
    `export const VERSION = '${version}';`,
    '',
  ].join('\n');
}
